version: '3.1'

services:
  nest:
    build: .
    ports:
      - "80:80"
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db 

volumes:
  db-data:
    driver: local